-- ============================================================================
-- 009_einvoice.sql — DEVRE DIŞI (superseded by 016_einvoice.sql)
-- ============================================================================
-- Bu migration başlangıçta e-Fatura tablolarını UUID birincil/yabancı anahtar
-- tipleriyle tanımlıyordu (company_id UUID, users(id) UUID, invoices(id) UUID).
-- Ancak gerçek şema bu varlıkları INT/SERIAL/BIGSERIAL kullanır:
--   companies.id INT (002), users.id INT (001), invoices.id BIGSERIAL (005)
-- Bu tip uyuşmazlığı yüzünden 009 hiçbir ortamda uygulanamıyordu (FK hatası).
--
-- Faz 6 (Finance — E-Fatura) bu modülü Clean Architecture ile yeniden yazdı;
-- şema doğru INT FK tipleriyle 016_einvoice.sql'de tanımlandı. 009 migration
-- geçmiş tutarlılığı için dosya olarak korunur ama artık NO-OP'tur.
--
-- Bkz: docs/MIGRATION_ROADMAP.md (Faz 6), docs/adr/0004 (e-fatura TS-exclude).
-- ============================================================================

-- (kasıtlı olarak boş — tüm DDL 016_einvoice.sql'e taşındı)
